VOLCENGINE_SYSTEM_VOICES = [
    {
        "voice_id": "zh_female_tianmeixiaoyuan_moon_bigtts",
        "name": "甜美校园",
        "gender": "female",
        "age_group": "young",
        "language": "chinese (mandarin)",
        "style": "甜美",
        "emotions": "neutral,calm,happy",
        "preview_url": None,
        "provider": "volcengine",
        "is_custom": False,
        "is_favorite": False,
        "source_label": "火山官方音色",
        "supports_favorite": False,
        "language_boost": None,
    },
    {
        "voice_id": "zh_female_linzhiling_mars_bigtts",
        "name": "知性女声",
        "gender": "female",
        "age_group": "adult",
        "language": "chinese (mandarin)",
        "style": "知性",
        "emotions": "neutral,calm,warm",
        "preview_url": None,
        "provider": "volcengine",
        "is_custom": False,
        "is_favorite": False,
        "source_label": "火山官方音色",
        "supports_favorite": False,
        "language_boost": None,
    },
    {
        "voice_id": "zh_male_zhixing",
        "name": "知性男声",
        "gender": "male",
        "age_group": "adult",
        "language": "chinese (mandarin)",
        "style": "沉稳",
        "emotions": "neutral,serious,calm",
        "preview_url": None,
        "provider": "volcengine",
        "is_custom": False,
        "is_favorite": False,
        "source_label": "火山官方音色",
        "supports_favorite": False,
        "language_boost": None,
    },
    {
        "voice_id": "zh_female_sweet",
        "name": "甜美女声",
        "gender": "female",
        "age_group": "young",
        "language": "chinese (mandarin)",
        "style": "活泼",
        "emotions": "happy,neutral",
        "preview_url": None,
        "provider": "volcengine",
        "is_custom": False,
        "is_favorite": False,
        "source_label": "火山官方音色",
        "supports_favorite": False,
        "language_boost": None,
    },
]


async def get_volcengine_system_voice_catalog() -> list[dict]:
    return [dict(item) for item in VOLCENGINE_SYSTEM_VOICES]
