"""add_episodes_project_settings_tables

Revision ID: 3d7fcd9b3f76
Revises: 096c39d0f051
Create Date: 2026-05-11 11:23:46.610418
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3d7fcd9b3f76'
down_revision: Union[str, None] = '096c39d0f051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'episode_number', name='uq_episode_number')
    )
    op.create_index(op.f('ix_episodes_project_id'), 'episodes', ['project_id'], unique=False)
    op.create_table('project_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('script_tone', sa.String(length=50), nullable=False),
    sa.Column('dialogue_density', sa.String(length=20), nullable=False),
    sa.Column('shot_rhythm', sa.String(length=20), nullable=False),
    sa.Column('character_consistency', sa.Boolean(), nullable=False),
    sa.Column('scene_consistency', sa.Boolean(), nullable=False),
    sa.Column('output_format', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_settings_project_id'), 'project_settings', ['project_id'], unique=True)
    op.add_column('projects', sa.Column('language', sa.String(length=20), server_default='zh', nullable=False))
    op.add_column('projects', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'notes')
    op.drop_column('projects', 'language')
    op.drop_index(op.f('ix_project_settings_project_id'), table_name='project_settings')
    op.drop_table('project_settings')
    op.drop_index(op.f('ix_episodes_project_id'), table_name='episodes')
    op.drop_table('episodes')
    # ### end Alembic commands ###
